name: ci
on:
  push:
    branches:
      - "**"
  workflow_run:
    workflows: ["update-snapshots"]
    types:
      - completed

defaults:
  run:
    # NOTE: A bit stricter than the default bash options used by GitHub Actions
    # (bash --noprofile --norc -e -o pipefail {0})
    shell: bash --noprofile --norc -euo pipefail {0}

# NOTE: Set concurrency for the current workflow to 1
concurrency: ci-${{ github.ref }}-${{ github.workflow }}

jobs:
  build-and-deploy:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: capralifecycle/actions-lib/check-runtime-dependencies@47562e75012b60f0fa5a40bf18d12ede746660d8 # v1.7.0

      - uses: capralifecycle/actions-lib/parse-config@47562e75012b60f0fa5a40bf18d12ede746660d8 # v1.7.0
        id: config
        with:
          config-file: ".ldp.json"

      - name: Install Task
        uses: go-task/setup-task@3be4020d41929789a01026e0e427a4321ce0ad44 # v2.0.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".node-version"

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: ".bun-version"

      - uses: capralifecycle/actions-lib/configure-aws-credentials@47562e75012b60f0fa5a40bf18d12ede746660d8 # v1.7.0
        id: aws
        with:
          aws-account-id: ${{ steps.config.outputs.accountId }}
          # NOTE: We use different roles on default and non-default branches
          aws-iam-role-name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && steps.config.outputs.roleName || steps.config.outputs.limitedRoleName }}

      - name: build project
        run: task build

      - name: check infra snapshots
        run: task check-snapshots

      - name: create and upload cloud assembly archive and metadata
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        id: upload-cloud-assembly
        uses: capralifecycle/actions-lib/upload-cloud-assembly@47562e75012b60f0fa5a40bf18d12ede746660d8 # v1.7.0
        with:
          aws-s3-bucket-name: ${{ steps.config.outputs.artifactBucket }}
          cdk-app-dir: "./packages/infrastructure"
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.aws.outputs.aws-session-token }}

      - name: trigger production deployment pipelines
        uses: capralifecycle/actions-lib/trigger-deployment-pipeline@47562e75012b60f0fa5a40bf18d12ede746660d8 # v1.7.0
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.aws.outputs.aws-session-token }}
        with:
          pipelines: ${{ steps.config.outputs.prodPipelines }}
          trigger-type: "cloud-assembly"
          aws-s3-bucket-name: ${{ steps.config.outputs.artifactBucket }}
          cloud-assembly-metadata-file: ${{ steps.upload-cloud-assembly.outputs.cloud-assembly-metadata-file }}
